2024-06-12 06:54:00.208 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-12 06:54:00.209 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-12 06:54:00.209 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-12 06:54:00.210 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-12 06:54:00.210 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-12 06:54:00.210 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration webrtc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-12 06:54:00.211 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-12 06:54:03.046 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from webrtc, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'webrtc' custom integration
2024-06-12 06:54:03.048 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] ServiceCallType was used from webrtc, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.ServiceCall instead, please report it to the author of the 'webrtc' custom integration
2024-06-12 06:54:03.075 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'browser_mod' accesses hass.helpers.storage. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from storage directly at custom_components/browser_mod/store.py, line 94: self.store = hass.helpers.storage.Store(STORAGE_VERSION, STORAGE_KEY), please report it to the author of the 'browser_mod' custom integration
2024-06-12 06:54:03.184 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'browser_mod' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/browser_mod/mod_view.py, line 24: hass.components.frontend.async_register_built_in_panel(, please report it to the author of the 'browser_mod' custom integration
2024-06-12 06:54:03.281 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.browser_mod.media_player.BrowserModPlayer'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.PAUSE|SEEK|VOLUME_SET|VOLUME_MUTE|TURN_ON|TURN_OFF|PLAY_MEDIA|STOP|PLAY|BROWSE_MEDIA: 152463>, please report it to the author of the 'browser_mod' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-06-12 06:54:03.468 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://alexa-api.nabucasa.com/access_token (400) 
2024-06-12 06:54:06.205 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.12/site-packages/stringcase.py:247: SyntaxWarning: invalid escape sequence '\W'
  return re.sub("\W+", "", string)

2024-06-12 06:54:06.398 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from nodered, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'nodered' custom integration
2024-06-12 06:54:06.403 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from nodered, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'nodered' custom integration
2024-06-12 06:54:07.172 ERROR (MainThread) [homeassistant.components.mqtt.client] Exception in _state_message_received when handling msg on 'frigate/Balcony_D47/recordings/state': 'ON'
Traceback (most recent call last):
  File "/config/custom_components/frigate/camera.py", line 241, in _state_message_received
    self._attr_is_recording = msg.payload.decode("utf-8") == "ON"
                              ^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?

2024-06-12 06:54:09.211 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.water_ph (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement 'ph' which is not a valid unit for the device class ('voltage') it is using; expected one of ['mV', 'V']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22
2024-06-12 06:54:09.419 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for retic @ 10.10.0.69: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='10.10.0.69', port=6053))]: [Errno 113] Connect call failed ('10.10.0.69', 6053) (SocketAPIError)
2024-06-12 06:54:12.282 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key) (offender: /usr/local/lib/python3.12/site-packages/tinytuya/core.py, line 944: time.sleep(0.1)), please create a bug report at https://github.com/make-all/tuya-local/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 447, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 449, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tuya_local/__init__.py", line 387, in async_setup_entry
    setup_device(hass, config)
  File "/config/custom_components/tuya_local/device.py", line 634, in setup_device
    device = TuyaLocalDevice(
  File "/config/custom_components/tuya_local/device.py", line 77, in __init__
    self._api = tinytuya.Device(dev_id, address, local_key)

2024-06-12 06:54:12.391 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 101: self._config = load_yaml(filename) (offender: /usr/src/homeassistant/homeassistant/util/yaml/loader.py, line 226: with open(fname, encoding="utf-8") as conf_file:), please create a bug report at https://github.com/make-all/tuya-local/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 447, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 449, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tuya_local/__init__.py", line 391, in async_setup_entry
    device_conf = get_config(entry.data[CONF_TYPE])
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 998, in get_config
    return TuyaDeviceConfig(fname)
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 101, in __init__
    self._config = load_yaml(filename)

2024-06-12 06:54:16.458 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key) (offender: /usr/local/lib/python3.12/site-packages/tinytuya/core.py, line 944: time.sleep(0.1)), please create a bug report at https://github.com/make-all/tuya-local/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 447, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 449, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tuya_local/__init__.py", line 387, in async_setup_entry
    setup_device(hass, config)
  File "/config/custom_components/tuya_local/device.py", line 634, in setup_device
    device = TuyaLocalDevice(
  File "/config/custom_components/tuya_local/device.py", line 77, in __init__
    self._api = tinytuya.Device(dev_id, address, local_key)

2024-06-12 06:54:16.566 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 101: self._config = load_yaml(filename) (offender: /usr/src/homeassistant/homeassistant/util/yaml/loader.py, line 226: with open(fname, encoding="utf-8") as conf_file:), please create a bug report at https://github.com/make-all/tuya-local/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 447, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 449, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tuya_local/__init__.py", line 391, in async_setup_entry
    device_conf = get_config(entry.data[CONF_TYPE])
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 998, in get_config
    return TuyaDeviceConfig(fname)
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 101, in __init__
    self._config = load_yaml(filename)

2024-06-12 06:54:16.576 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 101: self._config = load_yaml(filename) (offender: /usr/src/homeassistant/homeassistant/util/yaml/loader.py, line 226: with open(fname, encoding="utf-8") as conf_file:), please create a bug report at https://github.com/make-all/tuya-local/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 447, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 449, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tuya_local/__init__.py", line 402, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, entities)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2032, in async_forward_entry_setups
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2034, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2081, in _async_forward_entry_setup
    await entry.async_setup(self.hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 94, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 196, in async_setup_entry
    return await self._platforms[key].async_setup_entry(config_entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 333, in async_setup_entry
    return await self._async_setup_platform(async_create_setup_awaitable)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 363, in _async_setup_platform
    awaitable = create_eager_task(awaitable, loop=hass.loop)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/config/custom_components/tuya_local/switch.py", line 19, in async_setup_entry
    await async_tuya_setup_platform(
  File "/config/custom_components/tuya_local/helpers/config.py", line 22, in async_tuya_setup_platform
    cfg = get_config(discovery_info[CONF_TYPE])
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 998, in get_config
    return TuyaDeviceConfig(fname)
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 101, in __init__
    self._config = load_yaml(filename)

2024-06-12 06:54:16.607 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 101: self._config = load_yaml(filename) (offender: /usr/src/homeassistant/homeassistant/util/yaml/loader.py, line 226: with open(fname, encoding="utf-8") as conf_file:), please create a bug report at https://github.com/make-all/tuya-local/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tuya_local/__init__.py", line 402, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, entities)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2032, in async_forward_entry_setups
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2034, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2081, in _async_forward_entry_setup
    await entry.async_setup(self.hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 94, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 196, in async_setup_entry
    return await self._platforms[key].async_setup_entry(config_entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 333, in async_setup_entry
    return await self._async_setup_platform(async_create_setup_awaitable)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 363, in _async_setup_platform
    awaitable = create_eager_task(awaitable, loop=hass.loop)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/config/custom_components/tuya_local/switch.py", line 19, in async_setup_entry
    await async_tuya_setup_platform(
  File "/config/custom_components/tuya_local/helpers/config.py", line 22, in async_tuya_setup_platform
    cfg = get_config(discovery_info[CONF_TYPE])
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 998, in get_config
    return TuyaDeviceConfig(fname)
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 101, in __init__
    self._config = load_yaml(filename)

2024-06-12 06:54:16.854 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bfc620e66783c666f3rolyswitch_led already exists - ignoring light.xmas_led_2
2024-06-12 06:54:16.854 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bf192f9f4df5b4b4b9e9hwswitch_led already exists - ignoring light.xmas_led_1
2024-06-12 06:54:16.854 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bf3a3b88626842929bx1qvswitch_led already exists - ignoring light.breakfast_light
2024-06-12 06:54:16.855 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.52087318e09806cb20efswitch_1 already exists - ignoring switch.extension_lead_socket_1
2024-06-12 06:54:16.855 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.52087318c44f33cc54baswitch_1 already exists - ignoring switch.taz_light_socket_1
2024-06-12 06:54:16.855 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.54748347c4dd572310edswitch_1 already exists - ignoring switch.lava_lamp_socket_1
2024-06-12 06:54:16.856 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bfc620e66783c666f3rolyswitch_led already exists - ignoring light.xmas_led_2
2024-06-12 06:54:16.856 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bf192f9f4df5b4b4b9e9hwswitch_led already exists - ignoring light.xmas_led_1
2024-06-12 06:54:16.856 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bf3a3b88626842929bx1qvswitch_led already exists - ignoring light.breakfast_light
2024-06-12 06:54:16.857 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.52087318e09806cb20efswitch_1 already exists - ignoring switch.extension_lead_socket_1
2024-06-12 06:54:16.857 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.52087318c44f33cc54baswitch_1 already exists - ignoring switch.taz_light_socket_1
2024-06-12 06:54:16.857 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.54748347c4dd572310edswitch_1 already exists - ignoring switch.lava_lamp_socket_1
2024-06-12 06:54:16.860 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bfc620e66783c666f3rolyswitch_led already exists - ignoring light.xmas_led_2
2024-06-12 06:54:16.861 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bf192f9f4df5b4b4b9e9hwswitch_led already exists - ignoring light.xmas_led_1
2024-06-12 06:54:16.861 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bf3a3b88626842929bx1qvswitch_led already exists - ignoring light.breakfast_light
2024-06-12 06:54:16.861 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.52087318e09806cb20efswitch_1 already exists - ignoring switch.extension_lead_socket_1
2024-06-12 06:54:16.861 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.52087318c44f33cc54baswitch_1 already exists - ignoring switch.taz_light_socket_1
2024-06-12 06:54:16.862 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.54748347c4dd572310edswitch_1 already exists - ignoring switch.lava_lamp_socket_1
2024-06-12 06:54:16.863 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bfc620e66783c666f3rolyswitch_led already exists - ignoring light.xmas_led_2
2024-06-12 06:54:16.863 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bf192f9f4df5b4b4b9e9hwswitch_led already exists - ignoring light.xmas_led_1
2024-06-12 06:54:16.863 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bf3a3b88626842929bx1qvswitch_led already exists - ignoring light.breakfast_light
2024-06-12 06:54:16.865 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.52087318e09806cb20efswitch_1 already exists - ignoring switch.extension_lead_socket_1
2024-06-12 06:54:16.865 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.52087318c44f33cc54baswitch_1 already exists - ignoring switch.taz_light_socket_1
2024-06-12 06:54:16.865 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.54748347c4dd572310edswitch_1 already exists - ignoring switch.lava_lamp_socket_1
2024-06-12 06:54:17.001 WARNING (SyncWorker_11) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:54:17.302 WARNING (SyncWorker_7) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:54:22.209 WARNING (SyncWorker_3) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:54:26.580 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.simple_switch is taking over 10 seconds
2024-06-12 06:54:26.613 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.extension_lead is taking over 10 seconds
2024-06-12 06:54:27.445 WARNING (SyncWorker_9) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:54:49.025 WARNING (SyncWorker_18) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:54:49.251 WARNING (SyncWorker_4) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:54:53.543 WARNING (SyncWorker_7) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:54:59.269 WARNING (SyncWorker_9) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:55:03.565 WARNING (SyncWorker_15) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:55:03.689 WARNING (SyncWorker_8) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:55:04.690 WARNING (SyncWorker_6) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:55:08.902 WARNING (SyncWorker_21) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:55:14.833 WARNING (SyncWorker_16) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:55:19.129 WARNING (SyncWorker_15) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:55:45.766 WARNING (SyncWorker_23) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:55:47.083 WARNING (SyncWorker_14) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:55:49.679 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.browser_mod.media_player.BrowserModPlayer'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.PAUSE|SEEK|VOLUME_SET|VOLUME_MUTE|TURN_ON|TURN_OFF|PLAY_MEDIA|STOP|PLAY|BROWSE_MEDIA: 152463>, please report it to the author of the 'browser_mod' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-06-12 06:55:55.782 WARNING (SyncWorker_20) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:55:55.913 WARNING (SyncWorker_16) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:55:57.105 WARNING (SyncWorker_15) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:55:57.452 WARNING (SyncWorker_6) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:56:02.662 WARNING (SyncWorker_7) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:56:02.662 ERROR (MainThread) [custom_components.tuya_local.device] Failed to refresh device state for Taz_Light.
2024-06-12 06:56:06.132 WARNING (SyncWorker_19) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:56:06.134 ERROR (MainThread) [custom_components.tuya_local.device] Failed to refresh device state for Extension_Lead.
2024-06-12 06:56:06.168 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-06-12 06:56:15.508 WARNING (SyncWorker_19) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls hass.async_create_task from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassasync_create_task at custom_components/tuya_local/device.py, line 147: self._refresh_task = self._hass.async_create_task(self.receive_loop()), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:56:15.509 WARNING (SyncWorker_24) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls hass.async_create_task from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassasync_create_task at custom_components/tuya_local/device.py, line 147: self._refresh_task = self._hass.async_create_task(self.receive_loop()), please report it to the author of the 'tuya_local' custom integration
2024-06-12 06:56:15.566 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/device.py", line 147, in actually_start
    self._refresh_task = self._hass.async_create_task(self.receive_loop())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 805, in async_create_task
    self.verify_event_loop_thread("hass.async_create_task")
  File "/usr/src/homeassistant/homeassistant/core.py", line 447, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'tuya_local' calls hass.async_create_task from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassasync_create_task at custom_components/tuya_local/device.py, line 147: self._refresh_task = self._hass.async_create_task(self.receive_loop()). Please report it to the author of the 'tuya_local' custom integration.
2024-06-12 06:56:15.575 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.12/asyncio/base_events.py:1973: RuntimeWarning: coroutine 'TuyaLocalDevice.receive_loop' was never awaited
  handle = self._ready.popleft()

2024-06-12 06:56:15.575 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/device.py", line 147, in actually_start
    self._refresh_task = self._hass.async_create_task(self.receive_loop())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 805, in async_create_task
    self.verify_event_loop_thread("hass.async_create_task")
  File "/usr/src/homeassistant/homeassistant/core.py", line 447, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'tuya_local' calls hass.async_create_task from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassasync_create_task at custom_components/tuya_local/device.py, line 147: self._refresh_task = self._hass.async_create_task(self.receive_loop()). Please report it to the author of the 'tuya_local' custom integration.
2024-06-12 07:02:16.118 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-12 07:02:46.153 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Failed to connect to service MDNSServiceInfo(name='BRAVIA-4K-VH2-9e23b8263de40824b4f322cf304561c4._googlecast._tcp.local.'), retrying in 5.0s
2024-06-12 07:30:00.007 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'scheduler' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/scheduler/actions.py, line 401: async_track_state_change(, please create a bug report at https://github.com/nielsfaber/scheduler-component/issues
2024-06-12 09:03:11.600 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-12 09:03:41.609 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Failed to connect to service MDNSServiceInfo(name='BRAVIA-4K-VH2-9e23b8263de40824b4f322cf304561c4._googlecast._tcp.local.'), retrying in 5.0s
2024-06-12 09:27:36.208 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: [Errno 104] Connection reset by peer
2024-06-12 09:50:49.955 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for retic @ 10.10.0.69: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='10.10.0.69', port=6053))]: [Errno 111] Connect call failed ('10.10.0.69', 6053) (SocketAPIError)
2024-06-12 10:07:50.462 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: [Errno 104] Connection reset by peer
2024-06-12 10:07:50.472 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for retic @ 10.10.0.69: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='10.10.0.69', port=6053))]: [Errno 111] Connect call failed ('10.10.0.69', 6053) (SocketAPIError)
2024-06-12 10:18:14.653 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-12 11:47:00.364 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-12 11:47:00.364 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-12 11:49:07.148 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-12 11:49:07.148 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-12 11:51:13.931 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-12 11:51:13.932 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-12 11:53:20.716 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-12 11:53:20.716 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-12 11:55:24.236 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-12 11:55:24.236 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-12 11:58:35.898 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-12 11:58:35.898 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-12 12:00:46.096 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-12 12:02:47.107 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-12 12:02:47.108 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-12 12:04:57.313 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-12 12:05:27.349 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Failed to connect to service MDNSServiceInfo(name='BRAVIA-4K-VH2-9e23b8263de40824b4f322cf304561c4._googlecast._tcp.local.'), retrying in 5.0s
2024-06-12 12:33:14.649 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-12 13:03:47.563 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-12 13:04:17.581 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Failed to connect to service MDNSServiceInfo(name='BRAVIA-4K-VH2-9e23b8263de40824b4f322cf304561c4._googlecast._tcp.local.'), retrying in 5.0s
2024-06-12 15:47:27.749 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-12 15:47:57.770 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Failed to connect to service MDNSServiceInfo(name='BRAVIA-4K-VH2-9e23b8263de40824b4f322cf304561c4._googlecast._tcp.local.'), retrying in 5.0s
2024-06-12 15:48:17.885 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-12 16:12:29.259 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: Ping response not received after 90.0 seconds
2024-06-12 16:12:32.313 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for retic @ 10.10.0.69: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='10.10.0.69', port=6053))]: [Errno 113] Connect call failed ('10.10.0.69', 6053) (SocketAPIError)
2024-06-12 17:10:16.834 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: [Errno 104] Connection reset by peer
2024-06-12 18:07:11.970 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 411, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/components/airtouch4/climate.py", line 118, in _handle_coordinator_update
    return super()._handle_coordinator_update()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 491, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1000, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1126, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 464, in state
    hvac_mode = self.hvac_mode
                ^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/airtouch4/climate.py", line 139, in hvac_mode
    is_off = self._unit.PowerState == "Off"
             ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AirTouchAc' object has no attribute 'PowerState'
2024-06-12 18:24:36.667 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: Ping response not received after 90.0 seconds
2024-06-12 18:24:39.481 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for retic @ 10.10.0.69: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='10.10.0.69', port=6053))]: [Errno 113] Connect call failed ('10.10.0.69', 6053) (SocketAPIError)
2024-06-12 18:34:26.542 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: [Errno 104] Connection reset by peer
2024-06-12 18:35:06.783 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: [Errno 104] Connection reset by peer
2024-06-12 19:10:51.874 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: Ping response not received after 90.0 seconds
2024-06-12 19:10:54.969 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for retic @ 10.10.0.69: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='10.10.0.69', port=6053))]: [Errno 113] Connect call failed ('10.10.0.69', 6053) (SocketAPIError)
2024-06-12 19:48:42.001 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-12 19:49:12.035 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Failed to connect to service MDNSServiceInfo(name='BRAVIA-4K-VH2-9e23b8263de40824b4f322cf304561c4._googlecast._tcp.local.'), retrying in 5.0s
2024-06-12 21:01:19.923 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-12 21:21:20.304 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-12 21:41:19.906 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-12 21:59:17.023 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-12 21:59:47.041 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Failed to connect to service MDNSServiceInfo(name='BRAVIA-4K-VH2-9e23b8263de40824b4f322cf304561c4._googlecast._tcp.local.'), retrying in 5.0s
2024-06-12 22:01:20.271 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-12 22:01:45.418 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: Ping response not received after 90.0 seconds
2024-06-12 22:01:48.473 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for retic @ 10.10.0.69: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='10.10.0.69', port=6053))]: [Errno 113] Connect call failed ('10.10.0.69', 6053) (SocketAPIError)
2024-06-12 22:02:21.454 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-12 22:02:51.487 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Failed to connect to service MDNSServiceInfo(name='BRAVIA-4K-VH2-9e23b8263de40824b4f322cf304561c4._googlecast._tcp.local.'), retrying in 5.0s
2024-06-12 22:21:19.905 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-12 22:41:19.959 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-12 23:01:20.291 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-12 23:14:59.386 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-12 23:14:59.386 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-12 23:17:06.170 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-12 23:17:06.170 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-12 23:19:12.953 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-12 23:19:12.954 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-12 23:21:19.905 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-12 23:21:23.159 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-12 23:21:53.183 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Failed to connect to service MDNSServiceInfo(name='BRAVIA-4K-VH2-9e23b8263de40824b4f322cf304561c4._googlecast._tcp.local.'), retrying in 5.0s
2024-06-12 23:41:20.323 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 00:01:19.915 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 00:21:19.910 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 00:41:20.333 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 01:01:19.925 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 01:21:20.321 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 01:41:20.003 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 02:00:24.297 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-13 02:00:38.584 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Failed to connect to service MDNSServiceInfo(name='BRAVIA-4K-VH2-9e23b8263de40824b4f322cf304561c4._googlecast._tcp.local.'), retrying in 5.0s
2024-06-13 02:01:19.915 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 02:02:14.907 ERROR (Thread-4) [pychromecast.socket_client] [Kitchen display(10.10.0.31):8009] Error reading from socket.
2024-06-13 02:02:14.907 WARNING (Thread-4) [pychromecast.socket_client] [Kitchen display(10.10.0.31):8009] Error communicating with socket, resetting connection
2024-06-13 02:02:14.914 ERROR (Thread-4) [pychromecast.socket_client] [Kitchen display(10.10.0.31):8009] Failed to connect to service HostServiceInfo(host='10.10.0.31', port=8009), retrying in 5.0s
2024-06-13 02:21:20.327 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 02:39:23.577 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 02:39:23.577 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 02:41:19.927 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 02:41:30.361 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 02:41:30.362 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 02:42:43.805 ERROR (Thread-5) [pychromecast.socket_client] [Cave Nest(10.10.0.248):8009] Error reading from socket.
2024-06-13 02:42:43.806 WARNING (Thread-5) [pychromecast.socket_client] [Cave Nest(10.10.0.248):8009] Error communicating with socket, resetting connection
2024-06-13 02:42:43.811 ERROR (Thread-5) [pychromecast.socket_client] [Cave Nest(10.10.0.248):8009] Failed to connect to service HostServiceInfo(host='10.10.0.248', port=8009), retrying in 5.0s
2024-06-13 02:44:57.273 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 02:44:57.273 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 02:47:04.057 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 02:47:04.057 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 02:50:34.908 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-13 02:53:04.594 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-13 02:53:34.625 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Failed to connect to service MDNSServiceInfo(name='BRAVIA-4K-VH2-9e23b8263de40824b4f322cf304561c4._googlecast._tcp.local.'), retrying in 5.0s
2024-06-13 03:01:20.186 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-13 03:21:20.198 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-13 03:41:20.195 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-13 03:42:02.116 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Roborock S6 data
2024-06-13 04:01:20.190 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-13 04:21:20.576 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-13 04:41:20.196 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-13 05:01:20.171 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-13 05:21:20.606 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-13 05:41:20.208 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-13 06:01:20.609 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-13 06:07:44.761 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 06:07:44.761 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 06:09:54.953 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-13 06:11:58.457 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 06:11:58.458 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 06:14:08.670 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-13 06:16:09.281 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 06:16:09.281 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 06:18:19.507 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-13 06:20:23.033 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 06:20:23.033 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 06:21:20.226 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-13 06:22:33.229 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Heartbeat timeout, resetting connection
2024-06-13 06:23:03.253 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 06:41:20.213 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-13 06:48:51.319 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-13 07:02:18.015 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-13 07:02:32.313 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 07:44:17.966 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-13 07:44:21.049 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 09:33:30.479 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 09:33:30.479 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 09:33:33.560 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 09:35:37.081 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 09:35:37.081 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 09:35:40.152 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 09:37:42.009 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 09:37:42.010 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 09:37:45.081 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 09:39:48.602 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 09:39:48.602 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 09:39:51.672 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 09:41:55.193 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 09:41:55.194 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 09:41:58.265 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 09:44:01.786 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 09:44:01.786 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 09:44:04.857 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 09:47:15.117 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 09:47:15.117 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 09:47:18.201 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 09:49:20.057 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 09:49:20.057 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 09:49:23.128 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 09:52:43.399 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-13 09:52:46.457 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 10:18:27.991 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-13 12:33:27.965 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-13 12:44:22.279 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-13 12:44:25.336 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 13:14:42.617 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 13:14:42.617 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 13:14:45.688 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 13:17:55.963 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 13:17:55.963 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 13:17:59.032 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 13:19:59.211 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 13:19:59.211 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 13:20:02.296 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 13:22:12.489 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-13 13:22:15.544 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 15:48:20.445 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-13 16:30:26.170 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 16:30:26.170 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 16:30:29.240 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 16:33:39.503 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-13 16:33:42.584 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 16:35:42.994 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 16:35:42.994 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 16:35:46.105 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 16:37:49.625 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 16:37:49.625 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 16:37:52.696 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 16:39:56.217 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 16:39:56.217 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 16:39:59.290 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 16:42:02.809 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 16:42:02.809 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 16:42:05.881 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 16:44:09.401 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 16:44:09.402 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 16:44:12.472 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 16:46:15.993 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 16:46:15.993 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 16:46:19.064 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 16:48:22.586 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 16:48:22.587 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 16:48:25.657 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 16:50:35.847 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-13 16:50:38.904 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 16:53:12.161 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-13 16:53:15.256 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 17:13:05.892 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-13 17:13:05.892 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-13 17:13:05.893 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-13 17:29:42.939 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-13 17:29:42.939 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-13 17:29:42.940 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-13 17:41:32.110 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-13 17:41:32.111 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-13 17:41:32.111 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-13 17:41:32.111 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_4 is already used by switch.retic_valve_4 - ignoring switch.retic_valve_4
2024-06-13 17:41:32.111 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_5 is already used by switch.retic_valve_5 - ignoring switch.retic_valve_5
2024-06-13 17:41:32.111 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_6 is already used by switch.retic_valve_6 - ignoring switch.retic_valve_6
2024-06-13 17:41:32.112 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_7 is already used by switch.retic_valve_7 - ignoring switch.retic_valve_7
2024-06-13 17:51:11.517 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: [Errno 104] Connection reset by peer
2024-06-13 17:51:12.002 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-13 17:51:12.002 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-13 17:51:12.002 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-13 17:51:12.002 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_4 is already used by switch.retic_valve_4 - ignoring switch.retic_valve_4
2024-06-13 17:51:12.002 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_5 is already used by switch.retic_valve_5 - ignoring switch.retic_valve_5
2024-06-13 17:51:12.002 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_6 is already used by switch.retic_valve_6 - ignoring switch.retic_valve_6
2024-06-13 17:51:12.002 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_7 is already used by switch.retic_valve_7 - ignoring switch.retic_valve_7
2024-06-13 21:01:20.026 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 21:21:20.001 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 21:41:20.041 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 22:00:55.638 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-13 22:00:55.639 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-13 22:00:58.745 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 22:01:20.414 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 22:08:40.676 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-13 22:08:43.768 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-13 22:21:20.031 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 22:41:20.015 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 23:01:20.429 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 23:21:20.017 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-13 23:41:20.032 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-14 00:01:20.041 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-14 00:21:20.016 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-14 00:41:20.044 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-14 00:57:21.078 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 411, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/components/airtouch4/climate.py", line 118, in _handle_coordinator_update
    return super()._handle_coordinator_update()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 491, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1000, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1126, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 464, in state
    hvac_mode = self.hvac_mode
                ^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/airtouch4/climate.py", line 139, in hvac_mode
    is_off = self._unit.PowerState == "Off"
             ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AirTouchAc' object has no attribute 'PowerState'
2024-06-14 01:01:20.398 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-14 01:21:20.042 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-14 01:25:26.407 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-14 01:25:29.464 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-14 01:33:01.574 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-14 01:33:04.632 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-14 01:41:20.045 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-14 02:01:20.403 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-14 02:09:03.601 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-14 02:09:06.681 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-14 02:21:20.049 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-14 02:41:20.703 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-14 02:47:51.767 ERROR (Thread-5) [pychromecast.socket_client] [Cave Nest(10.10.0.248):8009] Error reading from socket.
2024-06-14 02:47:51.767 WARNING (Thread-5) [pychromecast.socket_client] [Cave Nest(10.10.0.248):8009] Error communicating with socket, resetting connection
2024-06-14 02:47:51.772 ERROR (Thread-5) [pychromecast.socket_client] [Cave Nest(10.10.0.248):8009] Failed to connect to service HostServiceInfo(host='10.10.0.248', port=8009), retrying in 5.0s
2024-06-14 03:01:20.292 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-14 03:21:20.279 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-14 03:41:20.680 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-14 03:42:02.114 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Roborock S6 data
2024-06-14 04:01:20.295 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-14 04:20:13.863 ERROR (Thread-4) [pychromecast.socket_client] [Kitchen display(10.10.0.31):8009] Error reading from socket.
2024-06-14 04:20:13.863 WARNING (Thread-4) [pychromecast.socket_client] [Kitchen display(10.10.0.31):8009] Error communicating with socket, resetting connection
2024-06-14 04:20:13.867 ERROR (Thread-4) [pychromecast.socket_client] [Kitchen display(10.10.0.31):8009] Failed to connect to service HostServiceInfo(host='10.10.0.31', port=8009), retrying in 5.0s
2024-06-14 04:21:20.673 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-14 04:41:20.301 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-14 05:01:20.333 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-14 05:02:02.041 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-14 05:02:02.042 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-14 05:02:05.112 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-14 05:04:15.313 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-14 05:04:18.425 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-14 05:21:20.743 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-14 05:41:20.319 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-14 06:01:20.330 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-14 06:21:20.266 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-14 06:41:20.692 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikin_10_10_0_53 are missing or not currently available
2024-06-14 06:44:22.652 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 411, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/components/airtouch4/climate.py", line 227, in _handle_coordinator_update
    return super()._handle_coordinator_update()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 491, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1000, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1126, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 464, in state
    hvac_mode = self.hvac_mode
                ^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/airtouch4/climate.py", line 253, in hvac_mode
    is_off = self._unit.PowerState == "Off"
             ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AirTouchGroup' object has no attribute 'PowerState'
2024-06-14 06:49:10.217 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-14 06:58:05.434 ERROR (MainThread) [snitun.multiplexer.core] Ping fails, no response from peer
2024-06-14 07:00:03.999 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: Ping response not received after 90.0 seconds
2024-06-14 07:00:07.097 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for retic @ 10.10.0.69: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='10.10.0.69', port=6053))]: [Errno 113] Connect call failed ('10.10.0.69', 6053) (SocketAPIError)
2024-06-14 07:02:22.759 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-14 07:02:25.848 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-14 08:12:26.745 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-14 08:12:26.745 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-14 08:12:29.817 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-14 08:13:16.171 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-14 08:13:16.171 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-14 08:13:16.171 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-14 08:13:16.172 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_4 is already used by switch.retic_valve_4 - ignoring switch.retic_valve_4
2024-06-14 08:13:16.172 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_5 is already used by switch.retic_valve_5 - ignoring switch.retic_valve_5
2024-06-14 08:13:16.172 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_6 is already used by switch.retic_valve_6 - ignoring switch.retic_valve_6
2024-06-14 08:13:16.172 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_7 is already used by switch.retic_valve_7 - ignoring switch.retic_valve_7
2024-06-14 08:15:53.657 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-14 08:15:53.657 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-14 08:15:56.728 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-14 08:19:27.009 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-14 08:19:27.009 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-14 08:19:30.105 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-14 08:22:50.387 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-14 08:22:53.497 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-14 08:26:15.805 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-14 08:26:15.805 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-14 08:26:18.873 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-14 08:30:27.577 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-14 08:30:27.577 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-14 08:30:30.648 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-14 08:32:40.835 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-14 08:32:43.897 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-14 08:34:55.112 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-14 08:34:58.169 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-14 09:57:19.731 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: [Errno 104] Connection reset by peer
2024-06-14 09:57:20.219 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-14 09:57:20.219 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-14 09:57:20.219 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-14 09:57:20.219 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_4 is already used by switch.retic_valve_4 - ignoring switch.retic_valve_4
2024-06-14 09:57:20.220 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_5 is already used by switch.retic_valve_5 - ignoring switch.retic_valve_5
2024-06-14 09:57:20.220 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_6 is already used by switch.retic_valve_6 - ignoring switch.retic_valve_6
2024-06-14 09:57:20.220 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_7 is already used by switch.retic_valve_7 - ignoring switch.retic_valve_7
2024-06-14 10:18:38.290 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-14 10:20:49.540 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-14 10:20:49.540 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-14 10:20:49.540 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-14 10:20:49.540 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_4 is already used by switch.retic_valve_4 - ignoring switch.retic_valve_4
2024-06-14 10:20:49.541 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_5 is already used by switch.retic_valve_5 - ignoring switch.retic_valve_5
2024-06-14 10:20:49.541 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_6 is already used by switch.retic_valve_6 - ignoring switch.retic_valve_6
2024-06-14 10:20:49.541 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_7 is already used by switch.retic_valve_7 - ignoring switch.retic_valve_7
2024-06-14 10:32:07.053 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-14 10:32:07.054 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-14 10:32:07.054 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-14 10:32:07.054 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_4 is already used by switch.retic_valve_4 - ignoring switch.retic_valve_4
2024-06-14 10:32:07.054 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_5 is already used by switch.retic_valve_5 - ignoring switch.retic_valve_5
2024-06-14 10:32:07.055 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_6 is already used by switch.retic_valve_6 - ignoring switch.retic_valve_6
2024-06-14 10:32:07.055 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_7 is already used by switch.retic_valve_7 - ignoring switch.retic_valve_7
2024-06-14 10:36:27.908 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: [Errno 104] Connection reset by peer
2024-06-14 10:36:28.600 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-14 10:36:28.600 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-14 10:36:28.600 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-14 10:36:28.601 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_4 is already used by switch.retic_valve_4 - ignoring switch.retic_valve_4
2024-06-14 10:36:28.601 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_5 is already used by switch.retic_valve_5 - ignoring switch.retic_valve_5
2024-06-14 10:36:28.601 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_6 is already used by switch.retic_valve_6 - ignoring switch.retic_valve_6
2024-06-14 10:36:28.601 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_7 is already used by switch.retic_valve_7 - ignoring switch.retic_valve_7
2024-06-14 10:39:21.383 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.daikinap55688 is taking over 10 seconds
2024-06-14 10:40:11.383 WARNING (MainThread) [homeassistant.components.climate] Updating daikin climate took longer than the scheduled update interval 0:01:00
2024-06-14 10:44:58.094 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: Ping response not received after 90.0 seconds
2024-06-14 10:45:01.177 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for retic @ 10.10.0.69: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='10.10.0.69', port=6053))]: [Errno 113] Connect call failed ('10.10.0.69', 6053) (SocketAPIError)
2024-06-14 12:03:35.497 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-14 12:03:38.552 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-14 12:33:38.286 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-14 14:29:38.472 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-14 14:29:38.472 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-14 14:29:38.472 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-14 14:29:38.473 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_4 is already used by switch.retic_valve_4 - ignoring switch.retic_valve_4
2024-06-14 14:29:38.473 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_5 is already used by switch.retic_valve_5 - ignoring switch.retic_valve_5
2024-06-14 14:29:38.473 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_6 is already used by switch.retic_valve_6 - ignoring switch.retic_valve_6
2024-06-14 14:29:38.473 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_7 is already used by switch.retic_valve_7 - ignoring switch.retic_valve_7
2024-06-14 15:31:04.643 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-14 15:31:07.705 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-14 15:33:17.907 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-14 15:33:21.017 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-14 15:41:59.318 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-14 15:41:59.318 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-14 15:41:59.318 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-14 15:41:59.318 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_4 is already used by switch.retic_valve_4 - ignoring switch.retic_valve_4
2024-06-14 15:41:59.319 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_5 is already used by switch.retic_valve_5 - ignoring switch.retic_valve_5
2024-06-14 15:41:59.319 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_6 is already used by switch.retic_valve_6 - ignoring switch.retic_valve_6
2024-06-14 15:41:59.319 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_7 is already used by switch.retic_valve_7 - ignoring switch.retic_valve_7
2024-06-14 15:44:44.884 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-14 15:44:44.884 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-14 15:44:44.884 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-14 15:44:44.885 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_4 is already used by switch.retic_valve_4 - ignoring switch.retic_valve_4
2024-06-14 15:44:44.885 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_5 is already used by switch.retic_valve_5 - ignoring switch.retic_valve_5
2024-06-14 15:44:44.885 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_6 is already used by switch.retic_valve_6 - ignoring switch.retic_valve_6
2024-06-14 15:44:44.885 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_7 is already used by switch.retic_valve_7 - ignoring switch.retic_valve_7
2024-06-14 15:48:21.239 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-14 15:52:52.001 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: [Errno 104] Connection reset by peer
2024-06-14 15:52:52.507 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-14 15:52:52.507 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-14 15:52:52.508 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-14 15:52:52.508 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_4 is already used by switch.retic_valve_4 - ignoring switch.retic_valve_4
2024-06-14 15:52:52.508 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_5 is already used by switch.retic_valve_5 - ignoring switch.retic_valve_5
2024-06-14 15:52:52.508 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_6 is already used by switch.retic_valve_6 - ignoring switch.retic_valve_6
2024-06-14 15:52:52.508 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_7 is already used by switch.retic_valve_7 - ignoring switch.retic_valve_7
2024-06-14 15:55:47.865 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-14 15:55:47.865 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-14 15:55:47.866 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-14 15:55:47.866 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_4 is already used by switch.retic_valve_4 - ignoring switch.retic_valve_4
2024-06-14 15:55:47.866 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_5 is already used by switch.retic_valve_5 - ignoring switch.retic_valve_5
2024-06-14 15:55:47.866 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_6 is already used by switch.retic_valve_6 - ignoring switch.retic_valve_6
2024-06-14 15:55:47.866 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_7 is already used by switch.retic_valve_7 - ignoring switch.retic_valve_7
2024-06-14 15:57:55.803 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-14 15:57:55.804 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-14 15:57:55.804 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-14 15:57:55.804 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_4 is already used by switch.retic_valve_4 - ignoring switch.retic_valve_4
2024-06-14 15:57:55.804 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_5 is already used by switch.retic_valve_5 - ignoring switch.retic_valve_5
2024-06-14 15:57:55.804 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_6 is already used by switch.retic_valve_6 - ignoring switch.retic_valve_6
2024-06-14 15:57:55.805 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_7 is already used by switch.retic_valve_7 - ignoring switch.retic_valve_7
2024-06-14 16:02:23.641 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-14 16:02:23.641 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-14 16:02:23.641 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-14 16:02:23.642 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_4 is already used by switch.retic_valve_4 - ignoring switch.retic_valve_4
2024-06-14 16:02:23.642 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_5 is already used by switch.retic_valve_5 - ignoring switch.retic_valve_5
2024-06-14 16:02:23.642 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_6 is already used by switch.retic_valve_6 - ignoring switch.retic_valve_6
2024-06-14 16:02:23.642 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_7 is already used by switch.retic_valve_7 - ignoring switch.retic_valve_7
2024-06-14 16:05:10.503 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-14 16:05:10.504 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-14 16:05:10.504 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-14 16:05:10.504 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_4 is already used by switch.retic_valve_4 - ignoring switch.retic_valve_4
2024-06-14 16:05:10.504 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_5 is already used by switch.retic_valve_5 - ignoring switch.retic_valve_5
2024-06-14 16:05:10.504 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_6 is already used by switch.retic_valve_6 - ignoring switch.retic_valve_6
2024-06-14 16:05:10.505 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_7 is already used by switch.retic_valve_7 - ignoring switch.retic_valve_7
2024-06-14 16:09:11.311 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_1 is already used by switch.retic_valve_1 - ignoring switch.retic_valve_1
2024-06-14 16:09:11.312 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_2 is already used by switch.retic_valve_2 - ignoring switch.retic_valve_2
2024-06-14 16:09:11.312 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_3 is already used by switch.retic_valve_3 - ignoring switch.retic_valve_3
2024-06-14 16:09:11.312 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_4 is already used by switch.retic_valve_4 - ignoring switch.retic_valve_4
2024-06-14 16:09:11.312 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_5 is already used by switch.retic_valve_5 - ignoring switch.retic_valve_5
2024-06-14 16:09:11.312 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_6 is already used by switch.retic_valve_6 - ignoring switch.retic_valve_6
2024-06-14 16:09:11.313 ERROR (MainThread) [homeassistant.components.switch] Platform esphome does not generate unique IDs. ID EC:62:60:B6:EE:A4-switch-valve_7 is already used by switch.retic_valve_7 - ignoring switch.retic_valve_7
2024-06-14 17:24:27.789 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: Ping response not received after 90.0 seconds
2024-06-14 17:24:30.841 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for retic @ 10.10.0.69: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='10.10.0.69', port=6053))]: [Errno 113] Connect call failed ('10.10.0.69', 6053) (SocketAPIError)
2024-06-14 22:05:14.977 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-14 22:05:29.273 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-15 00:42:07.694 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-15 00:42:10.809 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-15 02:06:19.406 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-15 02:06:22.520 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-15 02:46:32.917 ERROR (Thread-4) [pychromecast.socket_client] [Kitchen display(10.10.0.31):8009] Error reading from socket.
2024-06-15 02:46:32.917 WARNING (Thread-4) [pychromecast.socket_client] [Kitchen display(10.10.0.31):8009] Error communicating with socket, resetting connection
2024-06-15 02:46:32.922 ERROR (Thread-4) [pychromecast.socket_client] [Kitchen display(10.10.0.31):8009] Failed to connect to service HostServiceInfo(host='10.10.0.31', port=8009), retrying in 5.0s
2024-06-15 03:41:52.115 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Roborock S6 data
2024-06-15 03:57:21.289 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-15 03:57:21.289 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-15 03:57:24.345 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-15 04:00:34.621 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-15 04:00:34.622 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-15 04:00:37.689 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-15 04:02:39.545 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-15 04:02:39.546 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-15 04:02:42.616 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-15 04:05:52.870 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-15 04:05:52.871 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-15 04:05:55.961 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-15 04:09:06.219 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-15 04:09:09.304 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-15 04:11:19.516 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-15 04:11:22.616 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-15 04:20:47.727 ERROR (Thread-5) [pychromecast.socket_client] [Cave Nest(10.10.0.248):8009] Error reading from socket.
2024-06-15 04:20:47.728 WARNING (Thread-5) [pychromecast.socket_client] [Cave Nest(10.10.0.248):8009] Error communicating with socket, resetting connection
2024-06-15 04:20:47.732 ERROR (Thread-5) [pychromecast.socket_client] [Cave Nest(10.10.0.248):8009] Failed to connect to service HostServiceInfo(host='10.10.0.248', port=8009), retrying in 5.0s
2024-06-15 04:59:09.915 ERROR (MainThread) [homeassistant.components.solaredge] Timeout fetching <homeassistant.components.solaredge.coordinator.SolarEdgeOverviewDataService object at 0x7f23aa053c50> data
2024-06-15 06:49:29.668 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-15 06:58:26.866 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.daikinap55688_inside_temperature is taking over 10 seconds
2024-06-15 06:58:46.866 WARNING (MainThread) [homeassistant.components.sensor] Updating daikin sensor took longer than the scheduled update interval 0:00:30
2024-06-15 06:59:16.867 WARNING (MainThread) [homeassistant.components.sensor] Updating daikin sensor took longer than the scheduled update interval 0:00:30
2024-06-15 07:02:20.885 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-15 07:02:23.993 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-15 07:42:12.988 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-15 07:42:16.057 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-15 09:29:24.552 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: Ping response not received after 90.0 seconds
2024-06-15 09:29:27.609 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for retic @ 10.10.0.69: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='10.10.0.69', port=6053))]: [Errno 113] Connect call failed ('10.10.0.69', 6053) (SocketAPIError)
2024-06-15 10:18:50.285 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-15 11:11:58.874 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-15 11:12:01.977 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-15 11:39:23.348 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://alexa-api.nabucasa.com/access_token (400) 
2024-06-15 12:18:38.520 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 411, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/components/airtouch4/climate.py", line 118, in _handle_coordinator_update
    return super()._handle_coordinator_update()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 491, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1000, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1126, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 464, in state
    hvac_mode = self.hvac_mode
                ^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/airtouch4/climate.py", line 139, in hvac_mode
    is_off = self._unit.PowerState == "Off"
             ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AirTouchAc' object has no attribute 'PowerState'
2024-06-15 12:33:50.281 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-15 15:48:24.915 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-15 16:19:39.966 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities sensor.nodered_11ee0bb47c22109e are missing or not currently available
2024-06-15 19:00:10.915 ERROR (MainThread) [homeassistant.components.solaredge] Timeout fetching <homeassistant.components.solaredge.coordinator.SolarEdgeOverviewDataService object at 0x7f23aa053c50> data
2024-06-15 23:11:24.173 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-15 23:11:24.174 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-15 23:11:27.288 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-15 23:14:33.467 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: Ping response not received after 90.0 seconds
2024-06-15 23:14:36.537 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for retic @ 10.10.0.69: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='10.10.0.69', port=6053))]: [Errno 113] Connect call failed ('10.10.0.69', 6053) (SocketAPIError)
2024-06-15 23:20:08.029 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-15 23:20:11.129 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 02:33:36.702 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-16 02:33:39.768 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 02:44:17.772 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-16 02:44:20.857 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 03:18:45.354 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://alexa-api.nabucasa.com/access_token (400) 
2024-06-16 03:19:23.628 ERROR (MainThread) [snitun.multiplexer.core] Ping fails, no response from peer
2024-06-16 03:21:24.746 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-16 03:21:27.800 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 03:41:57.115 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Roborock S6 data
2024-06-16 03:44:05.920 ERROR (Thread-4) [pychromecast.socket_client] [Kitchen display(10.10.0.31):8009] Error reading from socket.
2024-06-16 03:44:05.920 WARNING (Thread-4) [pychromecast.socket_client] [Kitchen display(10.10.0.31):8009] Error communicating with socket, resetting connection
2024-06-16 03:44:05.926 ERROR (Thread-4) [pychromecast.socket_client] [Kitchen display(10.10.0.31):8009] Failed to connect to service HostServiceInfo(host='10.10.0.31', port=8009), retrying in 5.0s
2024-06-16 04:42:54.706 ERROR (Thread-5) [pychromecast.socket_client] [Cave Nest(10.10.0.248):8009] Error reading from socket.
2024-06-16 04:42:54.706 WARNING (Thread-5) [pychromecast.socket_client] [Cave Nest(10.10.0.248):8009] Error communicating with socket, resetting connection
2024-06-16 04:42:54.712 ERROR (Thread-5) [pychromecast.socket_client] [Cave Nest(10.10.0.248):8009] Failed to connect to service HostServiceInfo(host='10.10.0.248', port=8009), retrying in 5.0s
2024-06-16 06:12:21.580 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 06:12:21.581 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 06:12:24.697 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 06:14:34.912 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-16 06:14:38.009 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 06:49:48.110 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-16 07:02:20.550 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-16 07:02:23.609 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 09:20:02.210 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 09:20:02.210 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 09:20:05.304 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 09:23:28.509 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 09:23:28.509 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 09:23:31.576 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 09:26:40.194 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: [Errno 104] Connection reset by peer
2024-06-16 09:26:55.109 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 09:26:55.109 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 09:26:58.168 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 09:30:22.083 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 09:30:22.084 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 09:30:25.145 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 09:33:49.152 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 09:33:49.152 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 09:33:52.249 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 09:37:17.373 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 09:37:17.374 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 09:37:20.440 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 09:40:44.200 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 09:40:44.201 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 09:40:47.288 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 09:44:01.247 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-16 09:44:04.345 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 10:19:02.352 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-16 12:34:02.326 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-16 13:08:53.817 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 13:08:53.818 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 13:08:56.888 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 13:12:24.697 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 13:12:24.698 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 13:12:27.768 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 13:14:37.972 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-16 13:14:41.080 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 15:07:49.877 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities sensor.nodered_11ee0bb47c22109e are missing or not currently available
2024-06-16 15:48:29.958 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-16 16:58:01.920 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: [Errno 104] Connection reset by peer
2024-06-16 17:01:25.273 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-16 17:01:39.576 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 19:02:51.131 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: [Errno 104] Connection reset by peer
2024-06-16 20:13:21.381 WARNING (MainThread) [aioesphomeapi.connection] retic @ 10.10.0.69: Connection error occurred: Ping response not received after 90.0 seconds
2024-06-16 20:13:24.472 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for retic @ 10.10.0.69: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='10.10.0.69', port=6053))]: [Errno 113] Connect call failed ('10.10.0.69', 6053) (SocketAPIError)
2024-06-16 21:56:53.599 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-16 21:56:56.697 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 22:02:24.700 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-16 22:02:27.768 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 23:26:18.154 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 23:26:18.154 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 23:26:21.240 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 23:28:23.097 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 23:28:23.097 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 23:28:26.168 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 23:30:29.690 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 23:30:29.690 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 23:30:32.760 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 23:32:36.281 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 23:32:36.281 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 23:32:39.355 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 23:34:42.873 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 23:34:42.873 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 23:34:45.945 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 23:36:52.730 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 23:36:52.730 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 23:36:55.800 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 23:38:55.990 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 23:38:55.990 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 23:38:59.064 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 23:41:02.585 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-16 23:41:02.586 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-16 23:41:05.657 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-16 23:44:25.926 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-16 23:44:28.985 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 01:37:32.098 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.daikinap55688_inside_temperature is taking over 10 seconds
2024-06-17 01:37:52.098 WARNING (MainThread) [homeassistant.components.sensor] Updating daikin sensor took longer than the scheduled update interval 0:00:30
2024-06-17 01:38:22.099 WARNING (MainThread) [homeassistant.components.sensor] Updating daikin sensor took longer than the scheduled update interval 0:00:30
2024-06-17 01:58:02.529 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-17 01:58:05.624 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 02:50:02.259 ERROR (Thread-4) [pychromecast.socket_client] [Kitchen display(10.10.0.31):8009] Error reading from socket.
2024-06-17 02:50:02.259 WARNING (Thread-4) [pychromecast.socket_client] [Kitchen display(10.10.0.31):8009] Error communicating with socket, resetting connection
2024-06-17 02:50:02.265 ERROR (Thread-4) [pychromecast.socket_client] [Kitchen display(10.10.0.31):8009] Failed to connect to service HostServiceInfo(host='10.10.0.31', port=8009), retrying in 5.0s
2024-06-17 03:07:24.157 ERROR (Thread-5) [pychromecast.socket_client] [Cave Nest(10.10.0.248):8009] Error reading from socket.
2024-06-17 03:07:24.158 WARNING (Thread-5) [pychromecast.socket_client] [Cave Nest(10.10.0.248):8009] Error communicating with socket, resetting connection
2024-06-17 03:07:24.160 ERROR (Thread-5) [pychromecast.socket_client] [Cave Nest(10.10.0.248):8009] Failed to connect to service HostServiceInfo(host='10.10.0.248', port=8009), retrying in 5.0s
2024-06-17 03:11:21.202 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 03:11:21.203 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 03:11:24.280 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 03:13:34.483 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-17 03:13:37.592 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 03:16:07.498 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-17 03:16:10.552 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 03:42:02.115 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Roborock S6 data
2024-06-17 04:42:45.051 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-17 05:02:45.063 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-17 05:22:45.059 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-17 05:42:44.666 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-17 06:02:44.636 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-17 06:17:26.167 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 06:17:26.168 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 06:17:29.272 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 06:20:39.545 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-17 06:20:42.616 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 06:22:42.794 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 06:22:42.794 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 06:22:45.048 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-17 06:22:45.881 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 06:25:56.539 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 06:25:56.540 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 06:25:59.608 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 06:28:01.465 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 06:28:01.465 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 06:28:04.536 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 06:30:08.057 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 06:30:08.057 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 06:30:11.129 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 06:33:21.389 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 06:33:21.389 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 06:33:24.472 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 06:35:26.329 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 06:35:26.329 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 06:35:29.401 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 06:37:32.921 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 06:37:32.921 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 06:37:35.993 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 06:39:37.849 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 06:39:37.849 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 06:39:40.920 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 06:41:44.441 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 06:41:44.441 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 06:41:47.512 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 06:42:45.070 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-17 06:45:07.786 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-17 06:45:10.840 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 06:50:05.465 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-17 07:02:21.315 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-17 07:02:24.376 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 07:02:45.074 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.daikenap55688 are missing or not currently available
2024-06-17 08:32:44.372 ERROR (MainThread) [homeassistant.components.solaredge] Timeout fetching <homeassistant.components.solaredge.coordinator.SolarEdgeOverviewDataService object at 0x7f23aa053c50> data
2024-06-17 10:04:10.445 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 10:04:10.445 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 10:04:13.507 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 10:06:15.363 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 10:06:15.363 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 10:06:18.434 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 10:08:21.955 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 10:08:21.955 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 10:08:25.027 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 10:10:28.548 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 10:10:28.548 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 10:10:31.619 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 10:13:51.887 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-17 10:13:54.946 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 10:17:05.200 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-17 10:17:08.291 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 10:19:14.928 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-17 12:34:14.926 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-06-17 13:11:33.979 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.daikinap55688_inside_temperature is taking over 10 seconds
2024-06-17 13:11:53.980 WARNING (MainThread) [homeassistant.components.sensor] Updating daikin sensor took longer than the scheduled update interval 0:00:30
2024-06-17 13:12:23.982 WARNING (MainThread) [homeassistant.components.sensor] Updating daikin sensor took longer than the scheduled update interval 0:00:30
2024-06-17 13:32:20.518 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-17 13:32:23.619 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 13:34:23.811 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 13:34:23.811 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 13:34:26.883 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 13:37:33.699 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 13:37:33.700 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 13:37:36.770 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 13:40:47.020 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-17 13:40:50.114 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 13:42:50.298 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-06-17 13:42:50.298 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-06-17 13:42:53.378 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 13:45:03.578 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-06-17 13:45:06.691 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.207):8009] Failed to connect to service HostServiceInfo(host='10.10.0.207', port=8009), retrying in 5.0s
2024-06-17 15:46:35.841 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Failed to connect. No retries.
