2024-05-25 14:49:41.760 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-25 14:49:41.760 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-25 14:49:41.760 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-25 14:49:41.761 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-25 14:49:41.761 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-25 14:49:41.761 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration webrtc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-25 14:49:41.761 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-25 14:49:41.774 ERROR (MainThread) [homeassistant.helpers.entity_registry] 'climate' from integration airtouch4 has a non string unique_id '0', please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+airtouch4%22
2024-05-25 14:49:41.774 ERROR (MainThread) [homeassistant.helpers.entity_registry] 'climate' from integration airtouch4 has a non string unique_id '1', please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+airtouch4%22
2024-05-25 14:49:41.774 ERROR (MainThread) [homeassistant.helpers.entity_registry] 'climate' from integration airtouch4 has a non string unique_id '2', please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+airtouch4%22
2024-05-25 14:49:41.774 ERROR (MainThread) [homeassistant.helpers.entity_registry] 'climate' from integration airtouch4 has a non string unique_id '3', please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+airtouch4%22
2024-05-25 14:49:44.856 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://alexa-api.nabucasa.com/access_token (400)
2024-05-25 14:49:45.471 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from webrtc, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'webrtc' custom integration
2024-05-25 14:49:45.472 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] ServiceCallType was used from webrtc, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.ServiceCall instead, please report it to the author of the 'webrtc' custom integration
2024-05-25 14:49:45.736 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-05-25 14:49:47.148 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'browser_mod' accesses hass.helpers.storage. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from storage directly at custom_components/browser_mod/store.py, line 94: self.store = hass.helpers.storage.Store(STORAGE_VERSION, STORAGE_KEY), please report it to the author of the 'browser_mod' custom integration
2024-05-25 14:49:47.888 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.12/site-packages/stringcase.py:247: SyntaxWarning: invalid escape sequence '\W'
  return re.sub("\W+", "", string)

2024-05-25 14:49:47.939 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from nodered, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'nodered' custom integration
2024-05-25 14:49:47.943 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from nodered, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'nodered' custom integration
2024-05-25 14:49:50.449 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.browser_mod.media_player.BrowserModPlayer'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.PAUSE|SEEK|VOLUME_SET|VOLUME_MUTE|TURN_ON|TURN_OFF|PLAY_MEDIA|STOP|PLAY|BROWSE_MEDIA: 152463>, please report it to the author of the 'browser_mod' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-05-25 14:49:50.892 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.water_ph (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement 'ph' which is not a valid unit for the device class ('voltage') it is using; expected one of ['mV', 'V']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22
2024-05-25 14:49:51.048 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for retic @ 10.10.0.69: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='10.10.0.69', port=6053))]: [Errno 113] Connect call failed ('10.10.0.69', 6053) (SocketAPIError)
2024-05-25 14:49:51.914 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key) (offender: /usr/local/lib/python3.12/site-packages/tinytuya/core.py, line 944: time.sleep(0.1)), please create a bug report at https://github.com/make-all/tuya-local/issues
2024-05-25 14:49:53.303 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key) (offender: /usr/local/lib/python3.12/site-packages/tinytuya/core.py, line 944: time.sleep(0.1)), please create a bug report at https://github.com/make-all/tuya-local/issues
2024-05-25 14:49:53.500 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bfc620e66783c666f3rolyswitch_led already exists - ignoring light.xmas_led_2
2024-05-25 14:49:53.500 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bf192f9f4df5b4b4b9e9hwswitch_led already exists - ignoring light.xmas_led_1
2024-05-25 14:49:53.500 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bf3a3b88626842929bx1qvswitch_led already exists - ignoring light.breakfast_light
2024-05-25 14:49:53.501 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.52087318e09806cb20efswitch_1 already exists - ignoring switch.extension_lead_socket_1
2024-05-25 14:49:53.501 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.52087318c44f33cc54baswitch_1 already exists - ignoring switch.taz_light_socket_1
2024-05-25 14:49:53.501 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.54748347c4dd572310edswitch_1 already exists - ignoring switch.lava_lamp_socket_1
2024-05-25 14:49:53.503 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bfc620e66783c666f3rolyswitch_led already exists - ignoring light.xmas_led_2
2024-05-25 14:49:53.503 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bf192f9f4df5b4b4b9e9hwswitch_led already exists - ignoring light.xmas_led_1
2024-05-25 14:49:53.503 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bf3a3b88626842929bx1qvswitch_led already exists - ignoring light.breakfast_light
2024-05-25 14:49:53.504 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.52087318e09806cb20efswitch_1 already exists - ignoring switch.extension_lead_socket_1
2024-05-25 14:49:53.504 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.52087318c44f33cc54baswitch_1 already exists - ignoring switch.taz_light_socket_1
2024-05-25 14:49:53.504 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.54748347c4dd572310edswitch_1 already exists - ignoring switch.lava_lamp_socket_1
2024-05-25 14:49:53.505 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bfc620e66783c666f3rolyswitch_led already exists - ignoring light.xmas_led_2
2024-05-25 14:49:53.505 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bf192f9f4df5b4b4b9e9hwswitch_led already exists - ignoring light.xmas_led_1
2024-05-25 14:49:53.506 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bf3a3b88626842929bx1qvswitch_led already exists - ignoring light.breakfast_light
2024-05-25 14:49:53.507 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.52087318e09806cb20efswitch_1 already exists - ignoring switch.extension_lead_socket_1
2024-05-25 14:49:53.507 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.52087318c44f33cc54baswitch_1 already exists - ignoring switch.taz_light_socket_1
2024-05-25 14:49:53.507 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.54748347c4dd572310edswitch_1 already exists - ignoring switch.lava_lamp_socket_1
2024-05-25 14:49:53.508 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bfc620e66783c666f3rolyswitch_led already exists - ignoring light.xmas_led_2
2024-05-25 14:49:53.508 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bf192f9f4df5b4b4b9e9hwswitch_led already exists - ignoring light.xmas_led_1
2024-05-25 14:49:53.509 ERROR (MainThread) [homeassistant.components.light] Platform tuya does not generate unique IDs. ID tuya.bf3a3b88626842929bx1qvswitch_led already exists - ignoring light.breakfast_light
2024-05-25 14:49:53.510 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.52087318e09806cb20efswitch_1 already exists - ignoring switch.extension_lead_socket_1
2024-05-25 14:49:53.510 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.52087318c44f33cc54baswitch_1 already exists - ignoring switch.taz_light_socket_1
2024-05-25 14:49:53.510 ERROR (MainThread) [homeassistant.components.switch] Platform tuya does not generate unique IDs. ID tuya.54748347c4dd572310edswitch_1 already exists - ignoring switch.lava_lamp_socket_1
2024-05-25 14:49:54.897 WARNING (SyncWorker_1) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:49:54.900 WARNING (SyncWorker_0) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:50:00.190 WARNING (SyncWorker_10) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:50:00.192 WARNING (SyncWorker_14) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:50:03.405 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.simple_switch is taking over 10 seconds
2024-05-25 14:50:03.407 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.extension_lead is taking over 10 seconds
2024-05-25 14:50:26.918 WARNING (SyncWorker_14) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:50:26.946 WARNING (SyncWorker_4) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:50:27.232 WARNING (SyncWorker_13) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:50:27.455 WARNING (SyncWorker_15) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:50:36.962 WARNING (SyncWorker_12) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:50:37.471 WARNING (SyncWorker_14) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:50:42.585 WARNING (SyncWorker_11) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:50:42.892 WARNING (SyncWorker_10) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:50:47.813 WARNING (SyncWorker_3) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:50:48.247 WARNING (SyncWorker_4) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:51:15.271 WARNING (SyncWorker_2) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:51:15.379 WARNING (SyncWorker_3) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:51:15.767 WARNING (SyncWorker_8) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:51:15.995 WARNING (SyncWorker_7) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:51:25.395 WARNING (SyncWorker_4) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:51:26.011 WARNING (SyncWorker_2) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:51:30.816 WARNING (SyncWorker_15) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:51:30.816 ERROR (MainThread) [custom_components.tuya_local.device] Failed to refresh device state for Taz_Light.
2024-05-25 14:51:31.437 WARNING (SyncWorker_10) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:51:31.437 ERROR (MainThread) [custom_components.tuya_local.device] Failed to refresh device state for Extension_Lead.
2024-05-25 14:51:31.449 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-05-25 14:51:40.220 WARNING (SyncWorker_15) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_create_task from a thread at custom_components/tuya_local/device.py, line 147: self._refresh_task = self._hass.async_create_task(self.receive_loop()), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:51:40.222 WARNING (SyncWorker_15) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' calls async_create_task from a thread at custom_components/tuya_local/device.py, line 147: self._refresh_task = self._hass.async_create_task(self.receive_loop()), please report it to the author of the 'tuya_local' custom integration
2024-05-25 14:51:40.233 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/device.py", line 147, in actually_start
    self._refresh_task = self._hass.async_create_task(self.receive_loop())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 816, in async_create_task
    self.verify_event_loop_thread("async_create_task")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'tuya_local' calls async_create_task from a thread at custom_components/tuya_local/device.py, line 147: self._refresh_task = self._hass.async_create_task(self.receive_loop()). Please report it to the author of the 'tuya_local' custom integration.
2024-05-25 14:51:40.240 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.12/asyncio/base_events.py:1973: RuntimeWarning: coroutine 'TuyaLocalDevice.receive_loop' was never awaited
  handle = self._ready.popleft()

2024-05-25 14:51:40.240 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/device.py", line 147, in actually_start
    self._refresh_task = self._hass.async_create_task(self.receive_loop())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 816, in async_create_task
    self.verify_event_loop_thread("async_create_task")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'tuya_local' calls async_create_task from a thread at custom_components/tuya_local/device.py, line 147: self._refresh_task = self._hass.async_create_task(self.receive_loop()). Please report it to the author of the 'tuya_local' custom integration.
2024-05-25 14:56:55.345 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.browser_mod.media_player.BrowserModPlayer'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.PAUSE|SEEK|VOLUME_SET|VOLUME_MUTE|TURN_ON|TURN_OFF|PLAY_MEDIA|STOP|PLAY|BROWSE_MEDIA: 152463>, please report it to the author of the 'browser_mod' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-05-25 15:04:12.551 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-05-25 15:04:12.551 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-05-25 15:06:19.335 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-05-25 15:06:19.335 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-05-25 15:08:26.119 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error reading from socket.
2024-05-25 15:08:26.119 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Error communicating with socket, resetting connection
2024-05-25 15:10:59.674 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities sensor.nodered_11ee0bb47c22109e are missing or not currently available
2024-05-25 15:11:46.377 WARNING (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Heartbeat timeout, resetting connection
2024-05-25 15:12:09.030 ERROR (Thread-16) [pychromecast.socket_client] [TV(10.10.0.21):8009] Failed to connect to service HostServiceInfo(host='10.10.0.21', port=8009), retrying in 5.0s
2024-05-25 15:51:59.154 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities cover.0x94deb8fffeee9a39 are missing or not currently available
2024-05-25 16:30:59.762 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140356638352960] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1000, in entity_service_call
    raise result from None
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1605, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/airtouch4/climate.py", line 322, in async_turn_on
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 117, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 291, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 414, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/components/airtouch4/climate.py", line 227, in _handle_coordinator_update
    return super()._handle_coordinator_update()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 492, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1009, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1015, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 455, in state
    hvac_mode = self.hvac_mode
                ^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/airtouch4/climate.py", line 253, in hvac_mode
    is_off = self._unit.PowerState == "Off"
             ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AirTouchGroup' object has no attribute 'PowerState'
2024-05-25 17:50:00.003 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'scheduler' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/scheduler/actions.py, line 401: async_track_state_change(, please create a bug report at https://github.com/nielsfaber/scheduler-component/issues
2024-05-25 17:59:41.436 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://alexa-api.nabucasa.com/access_token (400)
